"""
PDF Service - Generate Professional PDF Reports
=================================================
Converts AI-generated text reports into downloadable PDF files.

This demonstrates how AI output can be formatted for real-world use -
official documents that can be printed, shared, and archived.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors


def generate_incident_pdf(incident: dict, output_dir: str = "reports") -> str:
    """
    Generate a professional PDF for a single incident.

    Input: incident dict with all fields (description, classification, AI report, etc.)
    Output: path to generated PDF file
    """

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # File path
    filename = f"report_{incident['report_number']}.pdf"
    filepath = os.path.join(output_dir, filename)

    # Create PDF document
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm
    )

    # Styles
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=18,
        spaceAfter=12,
        textColor=HexColor('#1B4F72')
    )

    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=13,
        spaceAfter=8,
        spaceBefore=16,
        textColor=HexColor('#2E86AB')
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=6,
        leading=14
    )

    meta_style = ParagraphStyle(
        'Meta',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#6C757D')
    )

    # Build PDF content
    elements = []

    # --- TITLE ---
    elements.append(Paragraph("INCIDENT REPORT", title_style))
    elements.append(Paragraph(
        f"Report Number: {incident.get('report_number', 'N/A')}",
        meta_style
    ))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        meta_style
    ))
    elements.append(Spacer(1, 0.5 * cm))

    # --- CLASSIFICATION TABLE ---
    classification_data = [
        ["Category", incident.get("category", "N/A")],
        ["Severity", incident.get("severity", "N/A")],
        ["Location", incident.get("location", "Not specified")],
        ["Time", incident.get("timestamp_extracted", "Not specified")],
        ["Status", incident.get("status", "open")],
        ["AI Confidence", f"{incident.get('confidence', 'N/A')}%"],
    ]

    table = Table(classification_data, colWidths=[4 * cm, 12 * cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), HexColor('#F0F4F8')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#DEE2E6')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.5 * cm))

    # --- ORIGINAL DESCRIPTION ---
    elements.append(Paragraph("ORIGINAL REPORT", header_style))
    elements.append(Paragraph(
        incident.get("description", "No description provided."),
        body_style
    ))

    # --- IMAGE ANALYSIS (if available) ---
    if incident.get("image_analysis"):
        elements.append(Paragraph("IMAGE ANALYSIS (AI-Generated)", header_style))
        elements.append(Paragraph(incident["image_analysis"], body_style))

    # --- AI REPORT ---
    if incident.get("ai_report"):
        elements.append(Paragraph("DETAILED ANALYSIS (AI-Generated)", header_style))
        # Split report into paragraphs
        for para in incident["ai_report"].split("\n"):
            if para.strip():
                elements.append(Paragraph(para.strip(), body_style))

    # --- AI REASONING ---
    if incident.get("ai_reasoning"):
        elements.append(Paragraph("CLASSIFICATION REASONING", header_style))
        elements.append(Paragraph(incident["ai_reasoning"], body_style))

    # --- FOOTER ---
    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "This report was generated by the AI-Powered Incident Report System. "
        "AI-generated content should be reviewed by authorized personnel before official use.",
        meta_style
    ))

    # Build PDF
    doc.build(elements)

    return filepath


def generate_monthly_pdf(report_text: str, month: str, stats: dict,
                         output_dir: str = "reports") -> str:
    """
    Generate a monthly summary PDF report for leadership.

    Input: AI-generated monthly report text + statistics
    Output: path to generated PDF file
    """

    os.makedirs(output_dir, exist_ok=True)

    filename = f"monthly_report_{month}.pdf"
    filepath = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Title'],
        fontSize=20, spaceAfter=12, textColor=HexColor('#1B4F72')
    )
    header_style = ParagraphStyle(
        'CustomHeader', parent=styles['Heading2'],
        fontSize=13, spaceAfter=8, spaceBefore=16, textColor=HexColor('#2E86AB')
    )
    body_style = ParagraphStyle(
        'CustomBody', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14
    )

    elements = []

    # Title
    elements.append(Paragraph(f"MONTHLY INCIDENT REPORT - {month}", title_style))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        ParagraphStyle('Meta', parent=styles['Normal'], fontSize=9, textColor=HexColor('#6C757D'))
    ))
    elements.append(Spacer(1, 0.5 * cm))

    # Stats table
    elements.append(Paragraph("STATISTICS SUMMARY", header_style))
    stats_data = [
        ["Total Incidents", str(stats.get("total", 0))],
        ["This Month", str(stats.get("this_month", 0))],
        ["This Week", str(stats.get("this_week", 0))],
    ]
    table = Table(stats_data, colWidths=[6 * cm, 10 * cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), HexColor('#F0F4F8')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#DEE2E6')),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.5 * cm))

    # AI Report content
    elements.append(Paragraph("DETAILED ANALYSIS", header_style))
    for para in report_text.split("\n"):
        if para.strip():
            elements.append(Paragraph(para.strip(), body_style))

    # Footer
    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "This report was generated by the AI-Powered Incident Report System.",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=HexColor('#999'))
    ))

    doc.build(elements)
    return filepath
